### ISSUE TITLE
basic auth on rss input

### ISSUE THREAD

**Issue by featheredtoast** [logstash-plugins/logstash-input-rss#7]
I have an rss feed that requires basic http auth to read from. However, I noticed that an auth-as-url stream isn't possible in faraday's implementation (see https://github.com/lostisland/faraday/issues/426 )

Would it be possible to add basic auth for feeds, either as a parsed URL stream here, or by adding user/pass attributes in the plugin itself?

**Comment by wwfalcon** [comment]
try https://USER:PASSWORD@host:ip

**Comment by featheredtoast** [comment]
The original ticket is about logstash input rss' dependency, faraday, not supporting that format.

see how the plugin uses it here:
https://github.com/logstash-plugins/logstash-input-rss/blob/master/lib/logstash/inputs/rss.rb#L42

and see that the user:passowrd@host format isn't supported via faraday here:
https://github.com/lostisland/faraday/issues/426
and here:
https://github.com/lostisland/faraday/issues/343

It still does not seem to be supported.

**Comment by wwfalcon** [comment]
you can add  user/pass attributes in the url as bellow:

```
input {
  rss {
    url => "https://USER:PASS@host:ip"
    interval => 300
  }
}

output {
    elasticsearch {
        hosts => "http://10.4.44.9:9294"
        index => "mbrain-rss-idx"
        document_type => "rss-doc"
    }
}
```
