### ISSUE TITLE
Error received from logstash-rss-input [`Error: tag <link> is too much in tag <channel>`]

### ISSUE THREAD

**Issue by bryankaraffa** [logstash-plugins/logstash-input-rss#9]
Receiving an error [`Error: tag <link> is too much in tag <channel>`] when adding my simple rss input configuration:

/etc/logstash/conf.d/02-rss-input.conf 

```
input {
  rss {
    url => "http://status.aws.amazon.com/rss/all.rss"
    interval => 6000
  }
}
```

Error received:

`Error: tag <link> is too much in tag <channel>`

Full Error Dump:

`{:timestamp=>"2015-09-02T20:41:30.595000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Rss url=>\"http://status.aws.amazon.com/rss/all.rss\", interval=>6000, debug=>false, codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">>\n  Error: tag <link> is too much in tag <channel>", :level=>:error}`

RSS Feed:  http://status.aws.amazon.com/rss/all.rss

```
<channel>
.....
<link>http://status.aws.amazon.com/</link>
<link rel="alternate" href="http://status.aws.amazon.com/rss/all.rss" type="application/rss+xml" title="Amazon Web Services Status Feed"/> 
.....
</channel>
```

Looking at the RSS feed itself, I am beginning to understand this error... it sounds like it's complaining because there are too many `<link>` elements within the `<channel>` element it's raising the error.

> RSS::TooMuchTagError
> Raised if there are more occurrences of the tag than expected.
> http://ruby-doc.org/stdlib-2.0.0/libdoc/rss/rdoc/RSS/TooMuchTagError.html

Thank you in advance!

**Comment by wirecutter313** [comment]
Bump, also having this issue with a number of RSS feeds.
